// Entries are independent: removing or reordering never changes their art.
const roomCategories = ['Techo', 'Pared', 'Suelo', 'Muebles'];
final roomConcepts = <Map<String, dynamic>>[
  roomItem(
    'ceiling_cloud',
    'Lámpara nube',
    'room_ceiling',
    'Techo',
    'cloud',
    '#FFF2DF',
    0,
  ),
  roomItem(
    'ceiling_petal',
    'Lámpara pétalo',
    'room_ceiling',
    'Techo',
    'petal',
    '#EFA0AB',
    1,
  ),
  roomItem(
    'ceiling_mobile',
    'Móvil de estrellas',
    'room_ceiling',
    'Techo',
    'mobile',
    '#BAA2DB',
    2,
  ),
  roomItem(
    'ceiling_lights',
    'Guirnalda de luz',
    'room_ceiling',
    'Techo',
    'lights',
    '#E2B957',
    3,
  ),
  roomItem(
    'ceiling_beams',
    'Vigas de madera',
    'room_ceiling',
    'Techo',
    'beams',
    '#C99D70',
    4,
  ),
  roomItem(
    'wall_floral',
    'Papel floral',
    'room_wall',
    'Pared',
    'floral',
    '#F6E8DD',
    5,
  ),
  roomItem(
    'wall_sage_panel',
    'Panel salvia',
    'room_wall',
    'Pared',
    'sage_panel',
    '#B8DCCB',
    6,
  ),
  roomItem(
    'wall_heart_frame',
    'Cuadro corazón',
    'room_decor',
    'Pared',
    'heart_frame',
    '#EFA0AB',
    7,
  ),
  roomItem(
    'wall_arch_mirror',
    'Espejo arco',
    'room_mirror',
    'Pared',
    'arch_mirror',
    '#C99D70',
    8,
  ),
  roomItem(
    'wall_memory_shelf',
    'Repisa de recuerdos',
    'room_shelf',
    'Pared',
    'memory_shelf',
    '#C99D70',
    9,
  ),
  roomItem(
    'floor_honey',
    'Parquet miel',
    'room_floor',
    'Suelo',
    'honey',
    '#D9B17E',
    10,
  ),
  roomItem(
    'floor_cream',
    'Tarima crema',
    'room_floor',
    'Suelo',
    'cream',
    '#EEDCC7',
    11,
  ),
  roomItem(
    'floor_rose',
    'Baldosa rosa',
    'room_floor',
    'Suelo',
    'rose_tile',
    '#DBA397',
    12,
  ),
  roomItem(
    'rug_cloud',
    'Alfombra nube',
    'room_rug',
    'Suelo',
    'cloud_rug',
    '#FFF2DF',
    13,
  ),
  roomItem(
    'rug_garden',
    'Alfombra jardín',
    'room_rug',
    'Suelo',
    'garden_rug',
    '#B8DCCB',
    14,
  ),
  roomItem(
    'furniture_cloud_bed',
    'Cama nube',
    'room_bed',
    'Muebles',
    'cloud_bed',
    '#B8DCCB',
    15,
  ),
  roomItem(
    'furniture_cuddle_chair',
    'Sillón abrazo',
    'room_chair',
    'Muebles',
    'cuddle_chair',
    '#EFA0AB',
    16,
  ),
  roomItem(
    'furniture_heart_table',
    'Mesa corazón',
    'room_table',
    'Muebles',
    'heart_table',
    '#D9B17E',
    17,
  ),
  roomItem(
    'furniture_nido_dresser',
    'Cómoda nido',
    'room_dresser',
    'Muebles',
    'nido_dresser',
    '#FFF2DF',
    18,
  ),
  roomItem(
    'furniture_companion_plant',
    'Planta compañera',
    'room_plant',
    'Muebles',
    'companion_plant',
    '#B8DCCB',
    19,
  ),
];

Map<String, dynamic> roomItem(
  String key,
  String name,
  String slot,
  String category,
  String style,
  String color,
  int? atlasIndex, {
  String? imageAsset,
}) => {
  'item_key': key,
  'name': name,
  'scope': 'room',
  'equip_slot': slot,
  'room_category': category,
  'appearance': {
    'style': style,
    'color': color,
    if (atlasIndex != null) 'atlas_index': atlasIndex,
    if (imageAsset != null) 'image_asset': imageAsset,
  },
  'collection': 'Nuestro rincón',
  'rarity': 'Común',
  'preview_only': true,
  'description': 'Una pieza de Nuestro rincón. Pruébala en tu habitación.',
};
